const data = {
    products:[
        {
            _id:'1',
            name:'Fox Fur Coat',
            category:'Real Fur Coats',
            image:'/images/666.jpg',
            price:360,
            brand:'Furland',
            rating:1,
            numReviews:10,
            description: 'High quality fur coat',
        },
        {
            _id:'2',
            name:'Rabbit Fur Coat',
            category:'Real Fur Coats',
            image:'/images/111.jpg',
            price:320,
            brand:'Furland',
            rating:3.5,
            numReviews:17,
            description: 'High quality fur coat',
        },
        {
            _id:'3',
            name:'Real Fur Coat',
            category:'Real Fur Coats',
            image:'/images/666.jpg',
            price:280,
            brand:'Furland',
            rating:4.0,
            numReviews:100,
            description: 'High quality fur coat',
        },
        {
            _id:'4',
            name:'Fox Fur Coat',
            category:'Real Fur Coats',
            image:'/images/111.jpg',
            price:360,
            brand:'Furland',
            rating:4.5,
            numReviews:13,
            description: 'High quality fur coat',
        },
        {
            _id:'5',
            name:'Chinchila Fur Coat',
            category:'Real Fur Coats',
            image:'/images/666.jpg',
            price:750,
            brand:'Furland',
            rating:4.5,
            numReviews:15,
            description: 'High quality fur coat',
        },
        {
            _id:'6',
            name:'Fox Fur Coat',
            category:'Real Fur Coats',
            image:'/images/111.jpg',
            price:120,
            brand:'Furland',
            rating:3.5,
            numReviews:10,
            description: 'High quality fur coat',
        },
    ],
};

export default data;